---

- name: Instalar Firewall
  shell:  dnf install firewalld -y

- name: Activar servicio firewalld
  shell: |
    systemctl enable firewalld
    systemctl start firewalld

- name: Activando masquerading en el firewall
  firewalld:
    masquerade: "yes"
    state: enabled
    permanent: yes
    immediate: yes

- name: Reglas del firewall para nfs
  shell: |
    firewall-cmd --permanent --add-service=nfs
    firewall-cmd --permanent --add-service=rpc-bind
    firewall-cmd --permanent --add-service=mountd
    firewall-cmd --reload