---

- name: Instalar Firewall
  dnf:
    name: firewalld
    state: latest
  become: true

- name: Activar servicio
  shell: |
    systemctl enable firewalld
    systemctl start firewalld
  become: true

- name : Firewall masquerading
  shell: |
    firewall-cmd --add-masquerade --permanent
    firewall-cmd --reload
  become: true

- name:  Configurando Iptables Kubernetes
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  become: true

- name : Aplicando reglas kubernetes
  shell: sysctl --system
  become: true
