---
- name: Instalar y ejecutar Docker
  shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  become: true

- name: Instalar paquetes Docker
  dnf:
    name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
    state: present
  become: true

- name: Instalar Docker
  dnf: 
    name: docker-ce
    state: present
  become: true

- name: Activar servicio
  systemd:
    name: docker
    state: started
    enabled: yes
    masked: no
  become: yes
