---

- name: Instalar Firewall
  shell:  dnf install firewalld -y

- name: Activar servicio
  shell: |
    systemctl enable firewalld
    systemctl start firewalld

- name: Allow masquerading in Firewalld
  firewalld:
    masquerade: "yes"
    state: enabled
    permanent: yes
    immediate: yes

- name: Allow Network Ports in Firewalld
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ master_ports if ('master' in group_names) else worker_ports }}"


- name:  Configurando Iptables Kubernetes
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  become: true

- name : Aplicando reglas kubernetes
  shell: sysctl --system
  become: true
