---

- name: Crear el repositorio para kubernetes
  file:
    path: /etc/yum.repos.d/kubernetes.repo
    state: touch
  become: true

- name:  Configurando la informacion del repositorio de kubernetes
  blockinfile: 
    path: /etc/yum.repos.d/kubernetes.repo
    block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl
  become: true

- name: Instalar Kubernetes
  shell: dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes


- name: Activar servicio
  systemd:
    name: kubelet
    state: started
    enabled: yes
    masked: no
  become: yes



