---
- name: Instalando kube-fannel.yml
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Instalando canal.yml
  command: kubectl apply -f https://docs.projectcalico.org/manifests/canal.yaml

- name: Instlando haproxy-ingress.yaml
  command: kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.5/deploy/haproxy-ingress.yaml