---
- name: Copiar token para nodos worker
  copy: src={{ join_token_file }} dest=kube_token

- name: Unir nodo al cluster
  shell: |
    kubeadm reset -f
    cat kube_token | tail -2 > initoken.sh
    sh initoken.sh
